#!/bin/bash

function visit_directory {
    pushd "$1" > /dev/null
    for file in *; do
        if [ -d "${file}" ]; then
            visit_directory "${file}"
        else
            if [ -h "${file}" -a ! -e "${file}" ]; then
                if [ ${file:0:1} != "/" ]; then
                    file="`pwd`/${file}"
                fi
                echo "${file}"
            fi
        fi
    done
    popd > /dev/null
}

for dir; do
    visit_directory "${dir}"
done
exit 0
