#!/bin/bash

for file; do
    if [ -f ${file} ]; then
        name=`basename ${file}`
        dir=`dirname ${file}` 
        read -i "${name}" -e new_name
        mv ${file} ${dir}/${new_name}
    fi
done
